### ISSUE TITLE
Add basic FLUX/CSV support

### ISSUE THREAD

**Issue by lmangani** [metrico/qryn-view#100]
Alongside the new datasources we should add basic support for the FLUX API with annotated CSV responses

Documentation for [Influx Annotated CSV](https://influxdata.github.io/iot-dev-guide/key-concepts.html#annotated-csv) and [supported datatypes](https://docs.influxdata.com/influxdb/v2.0/reference/syntax/annotated-csv/#annotations)

## Example Query on Deta Flux
```
curl -XPOST https://dev-wolf-flux-5qq.lmangani.deta.app/api/v2/query -sS \
  -H 'Accept:application/csv' \
  -H 'Content-type:application/vnd.flux' \
  -d 'import g "generate" g.from(start: 2022-04-01T00:00:00Z, stop: 2022-04-01T00:03:00Z, count: 3, fn: (n) => n)'
```
### Chart

The function returns annotated CSV in the FLUX format
```
#datatype,string,long,dateTime:RFC3339,long
#group,false,false,false,false
#default,_result,,,
,result,table,_time,_value
,,0,2022-04-01T00:00:00Z,1
,,0,2022-04-01T00:00:36Z,2
,,0,2022-04-01T00:01:12Z,3
```
(refers to #107 )
![image](https://user-images.githubusercontent.com/1423657/195990836-17508ccb-cb2e-47a0-98b2-c8d81157416f.png)

### Table Columns
Variant w/o timestamps (table)
```
#datatype,string,long,string,string
#group,false,false,false,false
#default,_result,,,
,result,table,one,1
,,0,two,2
,,0,three,3
,,0,four,4
,,0,five,5
```
![image](https://user-images.githubusercontent.com/1423657/195990781-be7506cb-c6fe-4c1d-b764-54dcce689d1b.png)

**Comment by jacovinus** [comment]
**Issue update:** 

Done: 
- API endpoint / request
- Parsing for table view

![Screenshot from 2022-10-25 18-13-34](https://user-images.githubusercontent.com/30432825/197830907-d281ce5b-8fd6-49ba-ae4d-3a4b2325f088.png)

Left:
- custom view for flux removing not used nd adjust a the editor.
- add headers settings to datasource settings (something needed for this case) 

Extras: 
 - tabs view for different viz types

**Comment by jacovinus** [comment]
closing as table and chart for Flux solved, opening new issue for tabs for different visualization types
