### ISSUE TITLE
Labels Selector for Query Builder

### ISSUE THREAD

**Issue by jacovinus** [metrico/qryn-view#101]
Add a Query builder compatible with the datasources: 
- Logs 
- Metrics

Sections: 
 - Labels selector

**Comment by jacovinus** [comment]
- added react-select library for input-multi-select
![chrome-capture-2022-9-19](https://user-images.githubusercontent.com/30432825/196628369-829d863b-b0fc-4839-8a38-4c9ec71d083f.gif)

**Comment by jacovinus** [comment]
- [ ] Metrics

- [ ] Logs

**Comment by Dletta** [comment]
Not blocked, assigned to status by error

**Comment by jacovinus** [comment]
closing as available at branch
