### ISSUE TITLE
Feature Request: Movable Time Window

### ISSUE THREAD

**Issue by Dletta** [metrico/qryn-view#105]
__The Dream__

If we have set a 1 hour window (last 1 hour), I'd like to be able to push back 1 hour or push forward 1 hour, to 'scroll' through the data one 'window size' at a time.

Let's discuss if this is something we want or not

**Comment by lmangani** [comment]
I think I've seen this before... 
![image](https://user-images.githubusercontent.com/1423657/199758132-7872147c-b3fb-4b67-af57-f61ce3ad7052.png)

**Comment by jacovinus** [comment]
![Screenshot from 2022-11-03 16-33-18](https://user-images.githubusercontent.com/30432825/199764890-4cb4d29b-fa02-4650-9310-7a0cbe4ba059.png)

**Comment by Dletta** [comment]
Zoom is making the window bigger, but that also often reduces the accuracy, so it's not the same purpose from my perspective

**Comment by lmangani** [comment]
Use the split screen to see the arrow version. It could even be a dropdown to jump < > with a variable time (1m, 5m, 15m)

**Comment by jacovinus** [comment]
**Resolution:**

![Screenshot from 2022-12-16 16-23-43](https://user-images.githubusercontent.com/30432825/208130893-709315ee-99d1-477b-8652-a080a814f97f.png)

- Added handlers for moving time window the range of time selected 
- Added handlers for going forwards and backwards in time a specific range of time
---
**Changes left:** 

![time-window](https://user-images.githubusercontent.com/30432825/208132053-5017f81c-7b5e-43cf-b53f-af260f4e94bb.png)

- [ ] A: join buttons with it's functionality (this space makes the buttons distant from it's matter that is the time picker)
- [ ] B: match arrow size with same symbol at the app. Take a look at other arrows size and make them match size

**Comment by jacovinus** [comment]
available at dev branch, closing
