### ISSUE TITLE
Fix: Resizable Editor

### ISSUE THREAD

**Issue by jacovinus** [metrico/qryn-view#109]
- Make the query editor resizable so user can set the height and dont take all space when the query is too large
- use react resizable for resizable div needs: https://www.npmjs.com/package/react-resizable

**Comment by jacovinus** [comment]
fixed with #118 , closing

**Comment by AlexeyOplachko** [comment]
Found Issue at resizing editor: the editor wont grow when the text jumps to new line (no auto grow)
