### ISSUE TITLE
Resizable split

### ISSUE THREAD

**Issue by AlexeyOplachko** [metrico/qryn-view#110]
Based on https://github.com/metrico/qryn-view/issues/109
Would be nice to have split resizable so you can do something like this if you need more view area for one of the sources
![image](https://user-images.githubusercontent.com/45398541/200523012-f38dce19-e584-43ab-8297-fc5f44cf438a.png)

**Comment by jacovinus** [comment]
fixed with #118 , closing

**Comment by AlexeyOplachko** [comment]
Found Issue at resizing panels: Would breake if too much data at editor or panel size is superior to previous size

**Comment by AlexeyOplachko** [comment]
Branch: https://github.com/metrico/qryn-view/tree/feature-resize

Related issues: #162 #176 #183
