### ISSUE TITLE
Feat: Autodetect dark/light mode

### ISSUE THREAD

**Issue by lmangani** [metrico/qryn-view#112]
Option to Auto-detect dark/light mode based on time of day.  For those lucky enough to have some light hours in the day.

**Comment by lmangani** [comment]
@AlexeyOplachko any progress?

**Comment by AlexeyOplachko** [comment]
[Demo here](https://cloki-view-demo-git-fork-metrico-feature-auto-theme-jacovinus.vercel.app/#step=5&apiUrl=https%3A%2F%2Fcloki-view-demo-git-fork-metrico-feature-auto-theme-jacovinus.vercel.app&theme=dark&time=&start=1669027419607000000&stop=1669027719607000000&isSubmit=false&isSplit=false&autoTheme=true&isEmbed=false&left=%255B%257B%2522id%2522%253A%2522Y8eB7kM7-L6drJbg4Y6d3%2522%252C%2522idRef%2522%253A%2522L-A%2522%252C%2522lastIdx%2522%253A1%252C%2522panel%2522%253A%2522left%2522%252C%2522queryType%2522%253A%2522range%2522%252C%2522limit%2522%253A100%252C%2522step%2522%253A5%252C%2522tableView%2522%253Afalse%252C%2522browserOpen%2522%253Afalse%252C%2522expr%2522%253A%2522%2522%252C%2522labels%2522%253A%255B%255D%252C%2522values%2522%253A%255B%255D%252C%2522response%2522%253A%257B%257D%257D%255D&right=%255B%257B%2522id%2522%253A%2522cwE8GX7AoyEq0PTQOIo2f%2522%252C%2522idRef%2522%253A%2522R-A%2522%252C%2522lastIdx%2522%253A1%252C%2522panel%2522%253A%2522right%2522%252C%2522queryType%2522%253A%2522range%2522%252C%2522limit%2522%253A100%252C%2522step%2522%253A5%252C%2522tableView%2522%253Afalse%252C%2522browserOpen%2522%253Afalse%252C%2522expr%2522%253A%2522%2522%252C%2522labels%2522%253A%255B%255D%252C%2522values%2522%253A%255B%255D%252C%2522response%2522%253A%257B%257D%257D%255D)

**Comment by lmangani** [comment]
Is this completed?

**Comment by AlexeyOplachko** [comment]
Yes, not merged into main though.

**Comment by jacovinus** [comment]
fixed and merged into dev branch
