### ISSUE TITLE
Logs: Rate and Interval Helper

### ISSUE THREAD

**Issue by lmangani** [metrico/qryn-view#115]
We currently have no option to calculate log rates without typing.

It would be nice to add an option to the log panel to wrap a quick rate around a selector w/ dynamic interval, ie:

![image](https://user-images.githubusercontent.com/1423657/201706643-f355d92a-e126-4dbd-a548-3198d25f15b6.png)

```
rate({host="homer"}[$__interval])
```

#### Interval

The `$__interval` is calculated using the time range and the width of the graph _(the number of pixels/points)_.

Approximate Calculation: `(to - from) / resolution`

**Comment by jacovinus** [comment]
merged at beta branch, closing
