### ISSUE TITLE
Resizable bug

### ISSUE THREAD

**Issue by AlexeyOplachko** [metrico/qryn-view#162]
found another bug with resizable editor
with a single panel, open and close inspector at left or right
should be a simple one

**Comment by jacovinus** [comment]
-  new bug from same issue:
  - Expand Editor (mannually increase height)
  - go back to min size mannualy
  Will note that the editor goes smaller in width

**Comment by jacovinus** [comment]
- [ ] Query container issue
        - at full view
          - open browser inspector
          - resize browser until having half screen with data view 
          - go back to full view
             Result: data view goes at fixed width.

**Comment by jacovinus** [comment]
- [ ] Editor state issue 
  - at any view: 
      - create a new query, fill editor
      - change datasurce at same query
      Result: will go back to initial query

**Comment by jacovinus** [comment]
closing as issues inside fixed
