### ISSUE TITLE
Full scroll down is clipped at feature resize

### ISSUE THREAD

**Issue by jacovinus** [metrico/qryn-view#183]
The views are clipped when there is more than a certain large at the resize feature, comparing to previous version.

**How to reproduce:**
- Open and make request of three different chart type queries at same panel (split view)

**Expected Behavior:**
- Views shouldn't be clipped, it should scroll till the end of view

- working on branch https://github.com/metrico/qryn-view/tree/feature-resize

**Comment by AlexeyOplachko** [comment]
Fixed
![chrome_2022-12-19_16-43-26](https://user-images.githubusercontent.com/45398541/208451432-8e961a5f-324c-452a-8dad-7396bfdc34d9.gif)
