### ISSUE TITLE
Multiple queries unintuitive behavior

### ISSUE THREAD

**Issue by AlexeyOplachko** [metrico/qryn-view#188]
When you have multiple queries, query bars are ordered in the same order you put them, but result containers are ordered with most recent one being last.
Needs feedback at which behavior would be correct

1. Current one
2. Reverse of current one, with most recently updated result container being in top position
3. Same order as query bars are ordered.

Demo gif: 
![chrome_2022-12-19_18-06-58](https://user-images.githubusercontent.com/45398541/208469613-8a45d52a-d20c-4cc3-86be-11fd873d4523.gif)

**Comment by Dletta** [comment]
My vote is 3. It makes no sense confusing the user by sorting results. Best to keep it in same order, so it is always the same order for the user.

A before B.
