### ISSUE TITLE
Adding Labels inside Log row generates same result for different labels

### ISSUE THREAD

**Issue by jacovinus** [metrico/qryn-view#194]
_Clicking at labels inside log row should generate same value inside editor_

How To reproduce:
 - Make a logs request inside a 'Logs' Query.
 - open one logs row.
 - click on '+' symbol for adding lables.
Result:
 - All labels added result in same value as first one.
Expected Behavior:
- Each value added should be reflected in editor.

![Screenshot from 2022-12-20 16-51-27](https://user-images.githubusercontent.com/30432825/208708732-80969d22-b755-473e-855f-c765c1996451.png)

**Comment by AlexeyOplachko** [comment]
Additional related bugs: 
- Pressing (-) doesn't replace `=` with `!=` if there's more than one label
- Pressing (+) when multiple labels are selected clears all of them

**Comment by jacovinus** [comment]
fixed at #199 , closing
