### ISSUE TITLE
Testing weekly Features

### ISSUE THREAD

**Issue by jacovinus** [metrico/qryn-view#215]
### Main Features to test from the last changelog

This features should be tested at:

- dev environment with an https API ```npm run https-start```
- local build ``` npm run build  && serve -s build```
- dev branch demo at https://cloki-view-demo-3o6c32bzt-jacovinus.vercel.app/

---

- [x] #217

1- Set time range to a specific relative time (1hour, 5minutes, etc)

2- make requests from queries

3- click on copy link dropdown and click on 'relative time'

4- paste url on another browser tab

**Result:** starting relative time should be same as previous.

---

- [x] **JSON raw response View**

1-  Open inspector inside the Browser, then go to Netrwork tab

2 - Make requests with Logs / Metrics and observe the requests and responses in network tab

3 - Open 'Raw' tab inside the view response

**Result:** The response preview inside network tab should match with JSON Raw view.

---

- [x] #218

- Open different queries ( Traces, Logs, Metrics...)

- Change data source type in between requests

**Result:**  Queries should change according to data source type

---

**Comment by Dletta** [comment]
### Found issues

#### Label Browser will open upon Keypressup

##### How to reproduce

- Close label browser manually
- Press 1 letter
- The Label Browser will open magically

#### Label Browser Button "Use Query" moves into Labels

See image below, the "Use Query" Button should be fixed at the bottom of the browser.
<img width="1365" alt="Screenshot 2022-12-28 at 12 11 36 PM" src="https://user-images.githubusercontent.com/5729042/209855930-f98e16df-bf74-4186-a384-7a62fa489a2a.png">

**Comment by Dletta** [comment]
##### Share Link

###### Current Behavior

I changed time to 'last 1 hour', clicked dropdown on 'share Link', checked 'relative time', clicked 'share link'.
Copied the link to a new tab. Found 'last 5 minutes'

##### Raw view confirmed working

##### Custom Select

Queries change per selected data source, however the image does not show inside the view.
It appears it should be seen after selection?

<img width="320" alt="Screenshot 2022-12-28 at 12 31 11 PM" src="https://user-images.githubusercontent.com/5729042/209857063-7daf9d6b-efae-48ca-a379-018c22d5b0c2.png">
<img width="283" alt="Screenshot 2022-12-28 at 12 31 18 PM" src="https://user-images.githubusercontent.com/5729042/209857070-f5491975-aa56-4c96-b737-2c0018cbc0f2.png">


I do see the images in the drop down however:

<img width="158" alt="Screenshot 2022-12-28 at 12 31 57 PM" src="https://user-images.githubusercontent.com/5729042/209857127-5c3ec972-2692-47d2-9196-f7e58919b2eb.png">
