### ISSUE TITLE
Log and Timestamp Spacing too small

### ISSUE THREAD

**Issue by Dletta** [metrico/qryn-view#228]
### Describe the bug.

<img width="564" alt="Screenshot 2023-01-05 at 2 44 13 PM" src="https://user-images.githubusercontent.com/5729042/210876419-b5195512-160d-4232-9537-cabcaa4bda24.png">

"UTCCan't" -> Should be "UTC Can't"

At least 1 space should be between the transformed timestamp and the log content.

In Chrome the timestamp is in a different font and a space seems to show, but there is no literal space and so when the font is not correct (Firefox), the spacing disappears

Even if Firefox is not a target browser, in Chrome we see that there is some kind of field overlap.

<img width="552" alt="Screenshot 2023-01-05 at 2 49 05 PM" src="https://user-images.githubusercontent.com/5729042/210877199-8f5d6d1c-dfe9-464b-8b87-f0a444016b9b.png">

### Reproduction

Execute a Logs query with any logs.

### Application version

v0.23.0

### Browser version

Firefox and Chrome

**Comment by jacovinus** [comment]
available at dev branch, closing
