### ISSUE TITLE
Table View Column Resize not working

### ISSUE THREAD

**Issue by Dletta** [metrico/qryn-view#229]
### Describe the bug.

<img width="232" alt="Screenshot 2023-01-05 at 2 52 28 PM" src="https://user-images.githubusercontent.com/5729042/210877994-d24b753e-0c05-4953-93c3-3c093f1a035a.png">

When the mouse hovers over the column resize area, the icon changes to the resize icon, however clicking and dragging does not resize the column.

### Reproduction

Make a query, switch to Table Tab and try to resize a column

### Application version

v0.23.0

### Browser version

Chrome Version 108.0.5359.124 (Official Build) (x86_64)

#### Depends on
- [x] #241

**Comment by jacovinus** [comment]
switching to tanstack table to fix inestability issues

**Comment by Dletta** [comment]
- [ ] #241

**Comment by jacovinus** [comment]
ready at new tanstack table component
