### ISSUE TITLE
Results border overlapped by result in all "result views"

### ISSUE THREAD

**Issue by Dletta** [metrico/qryn-view#230]
### Describe the bug.

On each result view tab (Logs, Table, Raw) the bottom border gets hidden by results.

(Table shown as example)

<img width="251" alt="Screenshot 2023-01-05 at 3 12 10 PM" src="https://user-images.githubusercontent.com/5729042/210880898-26e8c92c-deb6-49d9-befe-791141d2d3e9.png">

### Reproduction

Search for a result that requires a scroll.

Scroll to very bottom of the view and see the disappearing border.

### Application version

v0.23.0

### Browser version

Chrome and Firefox

**Comment by jacovinus** [comment]
available at dev branch, closing
