### ISSUE TITLE
Fix initial API URL by location

### ISSUE THREAD

**Issue by jacovinus** [metrico/qryn-view#235]
### Describe the bug.

We need an hability to detect location as datasource url.
 currently the way to add as default is with url query param 

### Reproduction

- Open a new instance os qryn view without setting datasources
- Labels are not showing

### Application version

0.23.0

**Comment by lmangani** [comment]
@jacovinus could you give this a test run?

**Comment by Dletta** [comment]
Joel is adding another step, I will assist with testing once he has added it.

**Comment by Dletta** [comment]
I did the following test:

- Run the demo in vercel (No qryn behind the origin), it correctly detected no qryn was there and opened data source settings menu
- I built dev and served it through a qryn instance. **It failed** it detected /ready succesfully, but did not fill in as far as I can tell any information to where to query to.

So not quite fixed.

- [ ] Fill in local url into the datasource details to activate local url for use

**Comment by jacovinus** [comment]
tested and available at dev branch, closing
