### ISSUE TITLE
Switch from React-table into Tanstack-table

### ISSUE THREAD

**Issue by jacovinus** [metrico/qryn-view#241]
### Description of the feature you're suggesting.

Current version of react-table is suited to react js,  as we went into react with typescript we should go in the updated version of react-table (tanstack react-table)

**Comment by jacovinus** [comment]
@Dletta , please review at: 
https://cloki-view-demo-i44oh91jd-jacovinus.vercel.app/

**Comment by Dletta** [comment]
I did first round of review and wrote you directly, please let me know if you find the same issue.

**Comment by jacovinus** [comment]
from review: wrap all data into column

**Comment by Dletta** [comment]
Current Review, looking great, ready to merge to master
