### ISSUE TITLE
Add basic auth to /ready request

### ISSUE THREAD

**Issue by jacovinus** [metrico/qryn-view#243]
### Describe the bug.

We should add basic auth capability for the /ready initial request for checking API

### Reproduction

1- Open settings 
2- Add an API with basic auth
3- Save settings 

expected result: 
request should be sent to /ready endpoint with basic auth data

### Application version

0.23.0

### Browser version

any

**Comment by jacovinus** [comment]
linked to #242

**Comment by Dletta** [comment]
From Discussion:
Currently we are expecting content-type header to be sent by /ready, however qryn-go does not send this (per LOKI API no content is usually provided)

**Comment by jacovinus** [comment]
closing as solved
