### ISSUE TITLE
Requests at window resize

### ISSUE THREAD

**Issue by jacovinus** [metrico/qryn-view#244]
### Describe the bug.

The window resize triggers unnecesary requests to API

### Reproduction

1- Make a request
2- Open network settings
3- Resize window
4- you should se more requests at network tab

### Application version

0.23.0

### Browser version

any

**Comment by Dletta** [comment]
From Review:

Solved, however biggest break point will reset active tab to Logs from Table

**Comment by jacovinus** [comment]
closing as marked as complete
