### ISSUE TITLE
Save tab state at window resize

### ISSUE THREAD

**Issue by jacovinus** [metrico/qryn-view#245]
### Describe the bug.

Opening a log and resizing window, and going into table or another tab, it goes back to initial tab

### Reproduction

1. Open a new query
2. switch to another tab than initial
3. resize window till mobile breakepoint or vice versa

will note tab goes back to original

### Application version

0.23.0

### Browser version

any

**Comment by Dletta** [comment]
https://user-images.githubusercontent.com/5729042/213507254-5885f882-fb59-4670-8d58-89cba5f69a15.mov

**Comment by jacovinus** [comment]
closing as available at dev branch
