### ISSUE TITLE
Style for Operation Builder Dropdown

### ISSUE THREAD

**Issue by Dletta** [metrico/qryn-view#264]
### Describe the bug.

<img width="383" alt="Screenshot 2023-02-07 at 1 20 49 PM" src="https://user-images.githubusercontent.com/5729042/217344428-df155881-2e4d-4da7-8710-2661c39c663e.png">

Dropdowns need styling still for Operations Builder

- [x] #265

Aggregation functions may need a rate or interval applied for example: Select Count inside aggregation currently returns the following query:
```
count({forwarder="vector"})
```
This will not return any data. However, what we should expect is the following query:
```
count(rate({forwarder="vector"} [$__interval]))
```
- [x] #266

Label Filter seems to reset the builder.

Apply a label-filter then either push 'Show Results' or 'Use Query' it appears to emit the query and then seems to clear the form and query (Firefox only)
- [x] #267

Firefox will show XML parsing errors for Option calls that return simply a status code. Chrome ignores them.
- [x] #268

<img width="504" alt="Screenshot 2023-02-07 at 2 39 31 PM" src="https://user-images.githubusercontent.com/5729042/217360432-33b38adb-c742-4c3d-a60b-ac26e301b464.png">

Strange reloads at times, where operators are emptied, however I could not reproduce at will.

### Reproduction

See up

### Application version

Branch (Operation Builder)

### Browser version

Firefox and Chrome

### Anything else?

Chrome works mostly fine, Firefox is low priority due to minimal users.

**Comment by jacovinus** [comment]
fixed at feature branch, closing
