### ISSUE TITLE
Logs volume chart

### ISSUE THREAD

**Issue by jacovinus** [metrico/qryn-view#274]
### Description of the feature you're suggesting.

Display a log volume chart whenever it should be available
- It should show the distribution of log lines over their selected time range.

- The operation under the hood should be: 
``sum by ({label}) (count_over_time({log query}[{interval}]))``

- the height of this chart should be compact

- should appear above the logs lines

- should refresh every time a new request is made at same query

**Comment by akvlad** [comment]
yes. Grafana does `sum by (level) (count_over_time(....[]))` . The only request is to make this feature optional. 
Because it can slow down all the requests.

**Comment by jacovinus** [comment]
closing as solved and available at dev branch
