### ISSUE TITLE
Locally run View may also attempt to call localhost again

### ISSUE THREAD

**Issue by Dletta** [metrico/qryn-view#279]
### Steps for recreation
I followed the steps to install and serve locally:
```shell
npm i

npm start
```

Navigating to the local version and adding a data source will still 'fail' (aka redirect me back to /datasources) because for some reason I see 2 calls going out, one succeeding ,to the chosen backend, and one failing, on the localhost api.

<img width="608" alt="Screenshot 2023-02-21 at 1 32 07 PM" src="https://user-images.githubusercontent.com/5729042/220440991-8343382f-65c4-4683-9147-447633876616.png">

### Expected Behavior

No call to localhost should be made if we have chosen a datasource.

**Comment by jacovinus** [comment]
fixed and available at dev branch, closing
