### ISSUE TITLE
Error Message does not persist over redirect

### ISSUE THREAD

**Issue by Dletta** [metrico/qryn-view#280]
### Procedure to recreate
Define a bad datasource (but valid url etc) and repeatedly click on save, to see the 'Network Error' toast notification.

We are redirected back to /datasources, but with the redirect the toast disappears as well.

### Expected Behavior

The toast notification stays globally or is fired inside /datasources instead. (Since we do redirect back on failed ready call)

**Comment by jacovinus** [comment]
fixed and available at dev branch, closing
