### ISSUE TITLE
Log Volume Chart colors and labels

### ISSUE THREAD

**Issue by Dletta** [metrico/qryn-view#283]
<img width="427" alt="Screenshot 2023-02-21 at 3 14 23 PM" src="https://user-images.githubusercontent.com/5729042/220460301-5685ca31-8f84-465f-bd44-bccf53279297.png">

Label is showing as unknown and the same color stays for the series.

If I turn Log Volume on when a chart is used (aka using count_over_time) then I see the following:
<img width="601" alt="Screenshot 2023-02-21 at 3 18 26 PM" src="https://user-images.githubusercontent.com/5729042/220460744-c69083cb-5f96-4d5f-8e1d-1520abdff211.png">

The legend uses ',' for separation, but the legend doesn't seem to support the character, so all the words are joined into one.

**Comment by jacovinus** [comment]
> <img alt="Screenshot 2023-02-21 at 3 14 23 PM" width="427" src="https://user-images.githubusercontent.com/5729042/220460301-5685ca31-8f84-465f-bd44-bccf53279297.png">
> 
> Label is showing as unknown and the same color stays for the series.
this behavior is expected as labels don't include 'level'
- try with any other else that has such as job="dummy-server"

**Comment by jacovinus** [comment]
fixed and available at dev branch, closing
