### ISSUE TITLE
Timestamp ordering does not work

### ISSUE THREAD

**Issue by akvlad** [metrico/qryn-view#301]
### Describe the bug.

"Backwards" button should order logs backwards when enabled.

### Reproduction

1. In logs view write a relevant query
2. Check the "backwards" direction button
3. Click "show results" button

ER: results should be sorted backwards
AR: the output is the same as for the "forward" direction

### Application version

v0.23.0

### Browser version

Firefox 110.0.1 (64-bit)

**Comment by jacovinus** [comment]
fixed and available at dev branch, closing
