### ISSUE TITLE
responcive UI bug

### ISSUE THREAD

**Issue by RFbkak37y3kIY** [metrico/qryn-view#321]
### Describe the bug.

- responcive UI bug
when resize the window, couple of components get outside of container.
![image](https://user-images.githubusercontent.com/10195789/231738661-b2347031-8ded-45d7-b5ca-00551b83468e.png)

![image](https://user-images.githubusercontent.com/10195789/231739688-9c86e94b-d07b-4f4d-89b7-60327d02155c.png)

### Reproduction

resize the window

### Application version

0.24.4

**Comment by RFbkak37y3kIY** [comment]
![image](https://user-images.githubusercontent.com/10195789/231806184-5753f682-2986-448a-b20d-5646466aa45c.png)

**Comment by jacovinus** [comment]
fixed and available at dev branch, closing
