### ISSUE TITLE
settings BUG

### ISSUE THREAD

**Issue by RFbkak37y3kIY** [metrico/qryn-view#322]
### Describe the bug.

if on DataSource / Logs set source link with '/' on the end, after that can not be possible to go back to home page

https://user-images.githubusercontent.com/10195789/231740883-7b49c805-30f9-4510-9708-2ff87faddedc.mp4

### Reproduction

on DataSource / Logs set source link with '/' on the end

### Application version

0.24.4

**Comment by jacovinus** [comment]
closing as available at dev branch
