### ISSUE TITLE
DataSource / Traces - doesn't work if api have on the end a "/"

### ISSUE THREAD

**Issue by RFbkak37y3kIY** [metrico/qryn-view#323]
### Describe the bug.

![image](https://user-images.githubusercontent.com/10195789/231795078-bb2d293a-f81b-458d-b20d-c2125d51de8b.png)

![image](https://user-images.githubusercontent.com/10195789/231795316-9ba90009-e74a-497a-b008-dd0faaa1b10d.png)

### Reproduction

DataSource / Traces - set slash on  the end a "/" of APi link

### Application version

0.24.4

**Comment by jacovinus** [comment]
closing as available at dev branch
