### ISSUE TITLE
"undefined" on DataRange

### ISSUE THREAD

**Issue by RFbkak37y3kIY** [metrico/qryn-view#324]
### Describe the bug.

![image](https://user-images.githubusercontent.com/10195789/231800189-609a335d-407c-48b4-ba33-8465f9664863.png)
![image](https://user-images.githubusercontent.com/10195789/231800551-c8a5fd9e-bf0a-47be-b113-48dc81433fe8.png)

### Reproduction

 - clear localStorage
 - refresh page

### Application version

0.24.4

**Comment by jacovinus** [comment]
fixed and available at dev branch, closing
