### ISSUE TITLE
Aggregation Widget

### ISSUE THREAD

**Issue by Dletta** [metrico/qryn-view#326]
#### Context

QRYN Reader Aggregation Reports feature should have a widget inside qryn-view

#### What

Reference previous work done to create a small UI to interact with the reports API.

Following components should be included:
- Logql or Promql Metric Query Input field
- Key-Value Label Input List (to specify new metric)
- Parameter Key and Parameter Value list (new line divided values for dynamic querying and labeling)
- Time selector input or re-use of time selected in qryn-view
- Progress based on a logql label: report="progress"

-It should be activated from an admin user (related to #333 )

### Anything else?

For reference discuss with @RFbkak37y3kIY and @akvlad

**Comment by jacovinus** [comment]
closing as available at feature branch
