### ISSUE TITLE
Please provide official docker image

### ISSUE THREAD

**Issue by rerime** [metrico/qryn-view#339]
### Description of the feature you're suggesting.

Please provide official docker image

**Comment by lmangani** [comment]
Hello @rerime 
qryn-view is distributed as part of qryn, inside the qryn official docker images. 
could you expand on the need for qryn-view in a stand-alone container?

**Comment by rerime** [comment]
@lmangani I didn't noticed it. Thx!
But why by default it didn't display anything?
I can see logs by grafana. But not via `qryn-view` ` localhost:3100`

**Comment by lmangani** [comment]
That's interesting. qryn-view is embedded. Could you confirm the version you're using and how you're running it?
When you browse to the / of port :3100 what do you receive?

**Comment by rerime** [comment]
Run in docker on remote server, then `ssh -L 9999:localhost:3100 remote` and open browser on localhost:9999
qryn_version: `v2.3.4`

```
 "Env": [
                    "PORT=3100",
                    "API_URL=http://localhost:3100",
                    "container=podman",
                    "NODE_VERSION=16.20.0",
                    "YARN_VERSION=1.22.19",
                    "BUILD=703030",
                    "NODE_OPTIONS=--max-old-space-size=256",
                    "LOG_LEVEL=error",
                    "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                    "TERM=xterm",
                    "HOME=/root",
                    "HOSTNAME=server
```

**Comment by lmangani** [comment]
please paste the output of `curl localhost:9999`

**Comment by rerime** [comment]
@lmangani  thx for support.
I've fix it by setup datasource url `http://localhost:9999`
