### ISSUE TITLE
Labels cardinality feature

### ISSUE THREAD

**Issue by jacovinus** [metrico/qryn-view#346]
**This feature should show metrics cardinality with statistics above total labels (key / value) combinations.**

- The main view should be a table
- Show total series in a visible placement (prefereblily behind queries input) 
- Show a list of labels with the amount of each (percentage of total if available) 
- Add label / value to query, clicking in each of the list, revealing new stats at table
-  Date selector

Base query: ``api/v1/status/tsdb``

**Comment by Dletta** [comment]
Reference here:
https://github.com/metrico/qryn-go/pull/134

**Comment by Dletta** [comment]
```
{
  "data": {
    "totalSeries": 2946,
    "totalLabelValuePairs": 987,
    "seriesCountByMetricName": null,
    "seriesCountByLabelName": [{
      "Name": "__ttl_days__",
      "Value": 2946
    }, {
      "Name": "sender",
      "Value": 2946
    }, {
      "Name": "container",
      "Value": 2946
    }],
    "seriesCountByFocusLabelValue": [{
      "Name": "elegant-albattani",
      "Value": 3
    }, {
      "Name": "jolly-antonelli",
      "Value": 3
    }, {
      "Name": "reverent-euler",
      "Value": 3
    }],
    "seriesCountByLabelValuePair": [{
      "Name": "__ttl_days__=25",
      "Value": 2946
    }, {
      "Name": "sender=logtest",
      "Value": 2946
    }, {
      "Name": "level=error",
      "Value": 982
    }],
    "labelValueCountByLabelName": [{
      "Name": "container",
      "Value": 982
    }, {
      "Name": "level",
      "Value": 3
    }, {
      "Name": "__ttl_days__",
      "Value": 1
    }]
  },
  "isPartial": false,
  "status": "success"
}
```

**Comment by Dletta** [comment]
Query URL:
```http://localhost:3216/api/v1/status/tsdb?date=2023-07-11&topN=3&match[]=%7Bsender%3D%22logtest%22%7D&focusLabel=container```
