### ISSUE TITLE
Datasource Self-Provisioning

### ISSUE THREAD

**Issue by lmangani** [metrico/qryn-view#363]
### Describe the bug.

When no datasource settings are presented, qryn-view should connect to the API using the same host/port it is served by.
Note: protocol, host and port should be determined from the currently served host

### Reproduction

1. open qryn on its default port 3100 (anonymous mode)
2. qryn-view does not self-provision to the serving URL

### Application version

latest

**Comment by jacovinus** [comment]
fixed at #365
