### ISSUE TITLE
Log Count

### ISSUE THREAD

**Issue by Dletta** [metrico/qryn-view#38]
Show the count of logs

maybe the same as Grafana, showing the limit and the actually returned number
<img width="480" alt="Screen Shot 2022-02-18 at 1 13 12 PM" src="https://user-images.githubusercontent.com/5729042/154747276-353783d0-89b1-47e4-a768-b6b87cf92ee8.png">

**Comment by jacovinus** [comment]
https://github.com/metrico/qryn-view/pull/97
