### ISSUE TITLE
Qryn-view behind a reverse proxy

### ISSUE THREAD

**Issue by akvlad** [metrico/qryn-view#388]
### Description of the feature you're suggesting.

According to the feature request https://github.com/metrico/qryn/issues/414 the use asks for the base path of qryn-view to be configurable on startup of the http server serving the qryn-view.

It appears that qryn-view hardcodes it's base path to be `/` . Can we figure out some way to change it? 
- It can be a JS script injected into the index.html to redefine the base path.
- It can be qryn-view functionality to figure out how it was requested.

Please keep in mind that base path should be applied to:
- all the static files we include in the app
- all the fake paths we use in the app: /plugins, /users, /datasources, /datasources/:ds

**Comment by lmangani** [comment]
I don't think the change should be in qryn-view itself but rather in the server hosting it.

**Comment by jacovinus** [comment]
> * all the fake paths we use in the app: /plugins, /users, /datasources, /datasources/:ds


We already solved the fake paths with the hash router
