### ISSUE TITLE
No "Cancel" button for DataSource Settings 

### ISSUE THREAD

**Issue by akvlad** [metrico/qryn-view#455]
### Describe the bug.

You can't cancel datasource settings change without saving.

### Reproduction

1. Open qryn-view
2. Go to "Datasource Settings"
3. Add custom HTTP Header
4. Start typing the header name

AR: The "Back" button is replaced to "Save", "Back" button is disappeared.
ER: There should be a way to go back without saving.

AR: There is a "Saved" green icon on the "Custom HTTP Headers" line, while "Save" button is also present
ER: The Datasource Settings page should either follow the "Autosave on edit" or "Manual save" concept, not both.

### Application version

3.2.7

### Browser version

Firefox 127.0.1

**Comment by jacovinus** [comment]
closing as fixed at #13
