### ISSUE TITLE
Timeline of the chart is complicated to use.

### ISSUE THREAD

**Issue by akvlad** [metrico/qryn-view#456]
### Describe the bug.

Timeline of the chart is very complicated to use.

### Reproduction

1. Connect qryn-view to the lab
2. Open the Search panel
3. Specify  `sum by (level) (rate({container="practical-mclean"}[1h]))` request
4. Set "Last week" time range
5. Run the request

AR: 
- The timeline of the graph doesn't display the time range it shows. 
- The timeline of the graph displays the time range of the data, not the time range of the request
ER: 
- The timeline (x coord) of the graph should contain the date at least once for each day it represents.
- The timeline should display all the requested time range even if there's no data there.

### Application version

3.2.7

### Browser version

Firefox 127.0.1

**Comment by jacovinus** [comment]
closing as fixed at https://github.com/gigapipehq/qryn-view/pull/13
