### ISSUE TITLE
Parsing Errors at Cardinality View

### ISSUE THREAD

**Issue by jacovinus** [metrico/qryn-view#469]
### Describe the bug.

We got a list of errors when clicking on multiple labels for the final result.

### Reproduction

Case 1: 
- click on a label - value option 
- click on a second label - value option
- delete the text 
- select another label value with same label as first time but with different value 
- Error: In this case both label values appear, should only appear the last action. 

Case 2: 
- Click on two different label-values
- Click on a third one
- Error: The second value gets erased

Case 3:  
- Click on two different label-values
- Click delete on the third one (without selecting) 
- Error: the dialog appears only with the first label-value selected and the last added when clicking on delete button

Case 4: 
- Click on two different values
- Click on a third one without value (just a label item)
- Error: it deletes the first two label-values 

Case 5:
- Click on any label-value
- Click on __name__
- Error: the __name__label gets replaced with styles and the query is broken 

Case 6: 
- same as Case 5, mostly underscores are broken

### Application version

qryn-view-v2.3.8

**Comment by akvlad** [comment]
Connected to #468
