### ISSUE TITLE
Qryn-view requests non-today delete request

### ISSUE THREAD

**Issue by akvlad** [metrico/qryn-view#490]
### Describe the bug.

A customer complained that delete request doesn't delete data.
According to the logs, the request was placed for the 10tn and 11th of July while he requested the 9th. 

The request was for 10-th and 11-th of July whereas the delete contract should cover one 24h from UTC midnight, the same period  as for cardinality request.

### Reproduction

N/A

### Application version

v3.2.10

**Comment by jacovinus** [comment]
closing as fixed at #492
