### ISSUE TITLE
Share Link Time to Relative Time

### ISSUE THREAD

**Issue by Dletta** [metrico/qryn-view#58]
In a future release, it would be great if relative time could be shared in a share link. 

At the moment, I may have 'Last 5 Minutes' selected, when I share the link, but what will be shared is the current time as end and 5 minutes ago as start.

**Comment by jacovinus** [comment]
_as is now, it shares the time of the shared data, to share the specific data that you are watching at screen._

 **for adding relative time should:**

- [ ] - extend link feature for supporting relative time 

- [ ] - load at first time with relative time or absolute time

- [ ] - add checkbox at share link menu for "Relative Time"

- [ ] - add checkbox also on history feature for links
