### ISSUE TITLE
Label View Enhancements

### ISSUE THREAD

**Issue by lmangani** [metrico/qryn-view#8]
- [ ] Labels should be sorted alphabetically
- [x] Label box should take a little less vertical space unless needed
- [x] Label selector box should auto-hide when search is performed to view any of the results

![image](https://user-images.githubusercontent.com/1423657/152588125-7bb4a4e8-8211-4319-89cf-555b1f80491e.png)

**Comment by jacovinus** [comment]
- label selection autohide when search, updated
